module_1/app/__init__.py
"""
This Python script is used to configure a Flask application which
contains URL routes within a 'views' blueprint.
"""
from flask import Flask # Import object of Flask class
from app.views import views # Import views blueprint

"""
This function Create Flask application with routes via a blueprint.
"""
def create_app():
    app = Flask(__name__)  # Create Flask app instance

    app.register_blueprint(views)   # Register the blueprint routes

    return app

module_1/app/views.py
"""
This Python script is used to declare three URL routes to web pages
(templates) in a 'views' blueprint.
"""
from flask import Blueprint, render_template

views = Blueprint("views", __name__)    # Create blueprint object

# Connect URL route '/' to home.html view using decorator
@views.route("/")
def home():
    return render_template("home.html")

# Connect URL route '/contact' to contact.html view using decorator
@views.route("/contact")
def contact():
    return render_template("contact.html")

# Connect URL route '/projects' to projects.html view using decorator
@views.route("/projects")
def projects():
   return render_template("projects.html")

module_1/app/templates/_navigation.html
<!-- Create included (partial) of HTML code for navigation -->
<!-- Excluding use of partials until future lessons
<nav class="navbar">
  <div class="nav-container">
  <ul class="nav-menu">
    <li><a href="{{ url_for('views.home') }}">Home</a></li>
    <li><a href="{{ url_for('views.contact') }}">Contact</a></li>
    <li><a href="{{ url_for('views.projects') }}">Projects</a></li>
  </ul>
  </div>
</nav>
-->

module_1/app/templates/base.html
<!-- This is the html base template to render child blocks-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Neil Fernandez's Personal Website</title>
    <!--Declare style sheet from static URL-->
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>
    <section>
        <header>
             <!--Extend with child template header-->
            {% block header %}{% endblock header %}
        </header>
        <main>
             <!--Display hint or extend with child template block-->
            {% block content %}<p>No templates to render.</p>{% endblock content %}
        </main>
    </section>
</body>
</html>

module_1/app/templates/contact.html
<!-- This is the html child template for the contact page-->

{% extends 'base.html' %} <!-- Connect child with parent template -->

<!-- Connect child with parent block using block's name header -->
{% block header %}
<!-- Navigation bar with currently active selection -->
<nav class="navbar">
  <div class="nav-container">
    <ul class="nav-menu">
      <li><a href="{{ url_for('views.home') }}">Home</a></li>
      <li><a href="{{ url_for('views.projects') }}">Projects</a></li>
      <li><a href="{{ url_for('views.contact') }}" class="active">Contact</a></li>
    </ul>
  </div>
</nav>
{% endblock header %}

 <!-- Connect child with parent block using block's name content -->
{% block content %}
 <!-- Reuse css class 'bio' etc. for consistent formatting of contact details -->
<section class="bio">
  <div class="bio-container">
    <div class="bio-text">
      <h1>Contact</h1>
      <p><strong>Contact me via email:</strong> <a href="mailto:nfern2@gmail.com" class="email-link">nfern2@gmail.com</a></p>
      <p><strong>Contact me via LinkedIn:</strong> <a href="https://www.linkedin.com/in/nkfernandez/" target="_blank" rel="noopener noreferrer">nkfernandez</a></p>
    </div>
</section>
{% endblock content %}

module_1/app/templates/home.html
<!-- This is the html child template for the home page-->

{% extends "base.html" %} <!-- Connect child with parent template -->

<!-- Connect child with parent block using block's name header -->
{% block header %}
<!-- Navigation bar with currently active selection -->
<nav class="navbar">
  <div class="nav-container">
    <ul class="nav-menu">
      <li><a href="{{ url_for('views.home') }}" class="active">Home</a></li>
      <li><a href="{{ url_for('views.projects') }}">Projects</a></li>
      <li><a href="{{ url_for('views.contact') }}">Contact</a></li>
    </ul>
  </div>
</nav>
{% endblock header %}

 <!-- Connect child with parent block using block's name content -->
{% block content %}
<section class="bio">
  <!-- Display bio text -->
  <div class="bio-container">
    <div class="bio-text">
      <h1>Neil Fernandez</h1>
      <h2>Engineer</h2>
      <p>
        Hi there!
      </p>
       <p>
        My name is Neil Fernandez and I am an Engineer working in banking,
           specialising in process automation and analytics.
      </p>
       <p>
        I hold a bachelor's honors degree in electrical and computer
           systems engineering and have a passion for robotics. I also
           teach mathematics and physics outide of my profession.
      </p>
       <p>
        I love the being in the outdoors and working with animals.
           I volunteer with a local wildlife not for profit
           to transport and care for sick and injured native wildlife.
      </p>
    </div>
    <!-- Display image -->
    <div class="bio-image">
      <img src="{{ url_for('static', filename='me.jpg') }}" alt="Photo of me and the dogs"/>
    </div>
  </div>
 </section>
{% endblock content %}

module_1/app/templates/projects.html
<!-- This is the html child template for the projects page-->

{% extends 'base.html' %} <!-- Connect child with parent template -->

<!-- Connect child with parent block using block's name header -->
{% block header %}
<!-- Navigation bar with currently active selection -->
<nav class="navbar">
  <div class="nav-container">
    <ul class="nav-menu">
      <li><a href="{{ url_for('views.home') }}">Home</a></li>
      <li><a href="{{ url_for('views.projects') }}" class="active">Projects</a></li>
      <li><a href="{{ url_for('views.contact') }}">Contact</a></li>
    </ul>
  </div>
</nav>
{% endblock header %}

 <!-- Connect child with parent block using block's name content -->
{% block content %}
 <!-- Reuse css class 'bio' etc. for consistent formatting of project details -->
<section class="bio">
  <div class="bio-container">
    <div class="bio-text">
      <h1>Projects</h1>
      <h2>Module 1: Create a Flask Web App</h2>
      <p><strong>Project Title:</strong> Flask Personal Web Application</p>
      <p><strong>Project Details:</strong> This project involved creating a personal web application
         using Flask as a landing page for my bio, contact details, and project details.
      </p>
      <p><strong>Project GitHub Link:</strong> <a href="https://github.com/neil-fernandez/jhu_software_concepts/tree/main/module_1" target="_blank" rel="noopener noreferrer">module 1</a></p>

    </div>
</section>
{% endblock content %}